### ISSUE TITLE
Voting turnout is not displayed in some cases

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/rezultate-vot-api#15]
https://staging.rezultatevot.ro/elections/8/turnout?division=locality&countyId=3325&localityId=37218
https://rezultatevot.ro/elections/8/turnout?division=locality&countyId=3325&localityId=37218

In the case above, there is no voting turnout displayed because the turnout object is not filled in by the API.
The turnout information is present, but in the results section.

To make the behavior consistent, the turnout object needs to be populated, so that the turnout card is displayed correctly in the client.

**Comment by thewindev** [comment]
Fixed
![image](https://user-images.githubusercontent.com/793611/94976643-49c90280-051e-11eb-8c87-33f804284d31.png)
