### ISSUE TITLE
504 returned on some queries for winners

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/rezultate-vot-api#18]
Some queries to the winners endpoint return 504 and the database connection times out.

Example: https://staging.rezultatevot.ro/elections/3/results?division=locality&countyId=2513

**Comment by thewindev** [comment]
Fixed
When this was reported, we didn't have a table for "winners". Now the request takes ~200ms.
![image](https://user-images.githubusercontent.com/793611/94976726-83017280-051e-11eb-8cd8-2f4a9082dd26.png)
