### ISSUE TITLE
[Newsfeed admin] Error 500 upon uploading an image

### ISSUE THREAD

**Issue by overeha** [code4romania/rezultate-vot-api#3]
![94279721-2f5abc00-ff55-11ea-99bf-4826e7242295](https://user-images.githubusercontent.com/45068169/94283237-6e8b0c00-ff59-11ea-9cd4-12c965fcc6af.png)

![94279694-2538bd80-ff55-11ea-9aae-eeaf56801dd2](https://user-images.githubusercontent.com/45068169/94283245-7185fc80-ff59-11ea-90f7-7662915bd3c0.png)

**Comment by RaduCStefanescu** [comment]
Tested on latest admin page, this is not replicating anymore.
