### ISSUE TITLE
Change labels for Alegeri locale 2016

### ISSUE THREAD

**Issue by overeha** [code4romania/rezultate-vot-api#47]
Primar - Turul 1 changes to Primar
Primar - Turul 2 changes to Primar - Alegeri speciale

![image](https://user-images.githubusercontent.com/45068169/94347235-23492a00-003b-11eb-94bc-ff6cac047cbe.png)

**Comment by thewindev** [comment]
![image](https://user-images.githubusercontent.com/793611/94802000-919d3c00-03ef-11eb-9178-89562fc84b2a.png)
Fixed
