### ISSUE TITLE
Change labels for Alegeri locale 2012

### ISSUE THREAD

**Issue by overeha** [code4romania/rezultate-vot-api#48]
Change Consiliul local - Turul 2 - Alegeri speciale to Consiliul local - Alegeri speciale
Change Primar Turul 1 to Primar
Change Primar Turul 2 - to Primar - Alegeri speciale

**Comment by thewindev** [comment]
Fixed
![image](https://user-images.githubusercontent.com/793611/94802340-27d16200-03f0-11eb-97e2-b191bc803a38.png)
