### ISSUE TITLE
Missing election ballot - Presedinte Consiliul Judetean - Alegeri locale 2008

### ISSUE THREAD

**Issue by overeha** [code4romania/rezultate-vot-api#50]
We need to find and display Presedinte Consiliul Judetean ballot in Alegeri locale 2008 - they were elected

![image](https://user-images.githubusercontent.com/45068169/94347655-c3548280-003e-11eb-8437-8c97f0f05d8f.png)

**Comment by thewindev** [comment]
![image](https://user-images.githubusercontent.com/793611/94976551-02db0d00-051e-11eb-86fd-4b71e163568e.png)
Fixed
