### ISSUE TITLE
Add new author in database

### ISSUE THREAD

**Issue by overeha** [code4romania/rezultate-vot-api#53]
Add Dragos Costache as author

bio: 
Cu experiență considerabilă atât în scris cât și în sectorul non-profit, Dragoș a devenit unul dintre membrii de bază ai Code for Romania în ultimii ani. Licențiat în științe politice (Universitatea din București) și cu două mastere în sociologie (Universiteit van Amsterdam) și antropologie socială (Stockholms Universitet) Dragoș are o experiență de teren foarte eclectică, de la politici de gen la discriminare digitală. Dragoș a lucrat în journalism, atât pentru publicații locale cât și pentru publicații internaționale dar și în marketing și comunicare, sectorul public sau ca project manager în sectorul non-profit.

![dragoscostache](https://user-images.githubusercontent.com/45068169/94358144-8a042d00-00a7-11eb-84a2-95accbf4480c.jpg)

**Comment by RaduCStefanescu** [comment]
This is done I belive, can we close it? @overeha
