### ISSUE TITLE
Alegeri locale 2012 - View National Presedinte CJ nu afiseaza date agregate in tabel 

### ISSUE THREAD

**Issue by overeha** [code4romania/rezultate-vot-api#54]
Pe view NATIONAL nu se trag datele in tabel la Presedinte de consiliu judetean

![image](https://user-images.githubusercontent.com/45068169/94358182-d5b6d680-00a7-11eb-991f-57347b2bcb20.png)

**Comment by RaduCStefanescu** [comment]
I think we can close this one, as it fixed:
<img width="1319" alt="Screenshot 2020-10-14 at 11 51 11" src="https://user-images.githubusercontent.com/15039873/95966322-a926ec80-0e13-11eb-80d7-6b4f93186c3a.png">
