### ISSUE TITLE
Alegeri locale 2008 - Presedinte CJ - nu exista in timeline

### ISSUE THREAD

**Issue by overeha** [code4romania/rezultate-vot-api#55]
Nu apare in timeline ballotul de Presedinte consiliu judetean

![image](https://user-images.githubusercontent.com/45068169/94358204-03038480-00a8-11eb-97a9-343521366b2a.png)

**Comment by thewindev** [comment]
Fixed
![image](https://user-images.githubusercontent.com/793611/94976402-9b24c200-051d-11eb-9849-fd628ae11723.png)
