### ISSUE TITLE
Deduplicate url for `BallotType.CountyCouncilPresident`

### ISSUE THREAD

**Issue by strainu** [code4romania/rezultate-vot-api#61]
There is no need to handle Bucharest separately for `BallotType.CountyCouncilPresident` in `GetFileUrl()`.

As a drive-by, do you really, really, really need to have the `CapitalCityMayor` ballot type? Looking at the frontend it doesn't seem so.

**Comment by thewindev** [comment]
Fixed in https://github.com/code4romania/rezultate-vot-api/pull/64
