### ISSUE TITLE
Mismatch between site and csv

### ISSUE THREAD

**Issue by strainu** [code4romania/rezultate-vot-api#63]
Time: 2020-09-28 20:20 UTC+3
URL: https://rezultatevot.ro/elections/95/results?division=locality&countyId=12913&localityId=12914
CSV: blob:https://prezenta.roaep.ro/fc926e2e-1e48-4c71-9542-af379238f14b (filename  pv_prov_uat_p_b_179141.csv) - I can provide the actual file
Elections: mayor, sector 1.

Results on site:

ARMAND CLOTILDE-MARIE-BRIGITTE | 35.506 | 41,06%
-- | -- | --
DANIEL TUDORACHE | 34.349 | 39,72%

Results in csv:

ARMAND CLOTILDE-MARIE-BRIGITTE | 35.508 | +2
-- | -- | --
DANIEL TUDORACHE | 34.353 | +4

I understand that the results are taken async from roaep.ro and mismatches might occur, but the numbers are too small to be from a single polling station. Likely different sources of data give different results or there are correction made at the source.

**Comment by thewindev** [comment]
Thank you for the report. We have a cache that invalidates every 10 minutes, so probably you got new results from the csv but the cache was still sending the old results. I checked the issue now and it seems we have the exact data from the csv.
![image](https://user-images.githubusercontent.com/793611/94790012-5d6d4f80-03de-11eb-912f-53b582f51460.png)
