### ISSUE TITLE
Candidates are duplicated in diaspora data for presidential elections

### ISSUE THREAD

**Issue by dapetcu21** [code4romania/rezultate-vot-api#84]
https://staging.rezultatevot.ro/elections/2/results?division=diaspora

<img width="354" alt="Screenshot 2020-10-09 at 15 48 09" src="https://user-images.githubusercontent.com/428060/95584748-e0c61b00-0a46-11eb-925b-2233ff460f5d.png">

**Comment by thewindev** [comment]
Fixed in #98
