### ISSUE TITLE
The County Council Leaders API returns 4 times the actual number of wins for a party

### ISSUE THREAD

**Issue by mmircea16** [code4romania/rezultate-vot-api#99]
See how it is displayed on the rezultate vot: https://rezultatevot.ro/elections/96/results 
<img width="1270" alt="Screen Shot 2020-10-18 at 17 10 25" src="https://user-images.githubusercontent.com/1107449/96373553-2086b400-1165-11eb-87f1-145ac16ca08a.png">

The numbers are exactly 4 times the actual values

Looking at the api: https://api.rezultatevot.ro/api/ballot?BallotId=96&Division=national the number match with the values in the `votes` field. 

Separately, question: should the actual correct value be present in the `votes` field or the `seats` field? I guess though any change in the api would need to be coordinated with a change in the frontend.

**Comment by RaduCStefanescu** [comment]
@thewindev Can you have a look on these numbers @mmircea16 has a point.

**Comment by RaduCStefanescu** [comment]
This one is fixed in the latest build.
